Support 308 Permanent Redirect.
libwww-perl/libwww-perl pull request #349
Opened 2020-09-15 22:00 UTC by galenhuntington

Closes #288 (for real).  Although the dependency version was bumped, the fix wasn't complete because this file wasn't updated.

2020-09-15 22:05 UTC, oalders commented
Thanks for his @galenhuntington! The PR just needs an appropriate entry in `Changes` in order for the build to run to completion.

2020-09-15 22:11 UTC, galenhuntington commented
Hm, still failing, does `META.json` need to be updated or something like that?

2020-09-16 00:05 UTC, karenetheridge requested changes

2020-09-16 00:05 UTC, karenetheridge commented on Changes
> +6.48      2020-09-15 21:58:57Z
This line (and the blank line before it) should be removed; the version and timestamp and filled in from the `{{$NEXT}}` template.

2020-09-16 14:45 UTC, oalders commented
This is failing on some older Perls:

```
t\00-report-prereqs.t .. ok
##[error]Bareword "HTTP::Status::RC_PERMANENT_REDIRECT" not allowed while "strict subs" in use at D:\a\libwww-perl\libwww-perl\lib/LWP/UserAgent.pm line 318.
##[error]Compilation failed in require at t\10-attrs.t line 5.
##[error]BEGIN failed--compilation aborted at t\10-attrs.t line 5.
t\10-attrs.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
##[error]Bareword "HTTP::Status::RC_PERMANENT_REDIRECT" not allowed while "strict subs" in use at D:\a\libwww-perl\libwww-perl\lib/LWP/UserAgent.pm line 318.
##[error]Compilation failed in require at t\redirect.t line 5.
##[error]BEGIN failed--compilation aborted at t\redirect.t line 5.
t\redirect.t ........... 
```

2020-09-16 15:16 UTC, galenhuntington commented
Do old versions of Perl somehow pull in old versions of `HTTP::Status`?  I must not understand the build process.

2020-09-16 21:04 UTC, galenhuntington commented
It's only old Perls on Windows too.

2020-09-16 21:17 UTC, galenhuntington commented
I don't know if it's an acceptable solution, but dropping the three pre-5.20 Windows Perl versions got us through.

2020-09-17 13:15 UTC, oalders commented
So, in https://github.com/libwww-perl/libwww-perl/runs/1120556913?check_suite_focus=true `HTTP::Status` is not getting upgraded. I guess this is because it meets the requirements in https://github.com/libwww-perl/libwww-perl/blob/master/cpanfile#L25

So, in that failing version we have `HTTP::Status             6.03`, which satisfies `requires 'HTTP::Status' => '6';`

We have in `dist.ini`:

```
[DynamicPrereqs]
:version = 0.018
; HTTP::Status 6.17 was buggy
-body = requires('HTTP::Status', '6.18') if has_module('HTTP::Status', '6.17');
```
but that only deals with the case where `6.17` has been installed. It looks like we need to bump the minimum version in `cpanfile`.

2020-09-20 14:47 UTC, oalders commented
I took a closer look at all of this. We've been trying to be pretty conservative with bumping prereqs. I think bumping to 6.07 rather than 6.18 would fix this as well. Could we try that? https://metacpan.org/changes/distribution/HTTP-Message#L92-103

2020-09-20 15:23 UTC, oalders commented
🚀 

Thanks @galenhuntington! I'm going to squash these and commit them from the command line, so I will close this shortly, once I've released a new version. Thanks so much for this!

2020-09-20 15:29 UTC, oalders commented
https://metacpan.org/pod/release/OALDERS/libwww-perl-6.48/lib/LWP/UserAgent.pm

2020-09-20 15:29 UTC, closed without merging