Documentation updates for https://github.com/libwww-perl/libwww-perl/issues/448#
libwww-perl/libwww-perl pull request #457
Opened 2024-03-01 00:26 UTC by rshingleton

Updates to reflect changes with regards to how PERL_LWP_SSL_VERIFY_HOSTNAME no longer disables all SSL verifications

[Issue #448 - $ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0 seems to be ignored](https://github.com/libwww-perl/libwww-perl/issues/448#)

2024-03-01 17:17 UTC, noxxi requested changes
Thanks for the documentation update. I've added a comment with fixes on typos and a recommendation for a different wording.

2024-03-01 17:17 UTC, noxxi commented on lib/LWP/UserAgent.pm
typos: 
verifacation -> verification
verications -> verifications
SSl -> SSL

wording:
"To disable SSl verifications the SSL_verify_mode option can be disabled using the ssl_opts. . For example: ..." -> To disable all SSL verification use the C<SSL_verify_mode> option as following: ...

2024-03-01 18:09 UTC, rshingleton commented on lib/LWP/UserAgent.pm
That will teach me to have a conversation with my 10 year old and attempt to write documentation at the same time.

2024-03-01 18:57 UTC, oalders commented on lib/LWP/UserAgent.pm
This is confirmed in the failing test:

```text
#   Failed test 'POD spelling for lib/LWP/UserAgent.pm'
#   at xt/author/pod-spell.t line 11.
# Errors:
#     SSl
#     certifate
#     verications
#     verifaction
#     verifications
```

2024-03-01 20:28 UTC, rshingleton commented on lib/LWP/UserAgent.pm
Got it. I honestly just committed it an walked away without looking back last night without checking the tests. I'll be more attentive in the future. Thanks for taking care of it.

2024-03-03 13:04 UTC, noxxi approved these changes

2024-03-03 13:05 UTC, noxxi approved these changes

2024-03-11 00:53 UTC, oalders commented
Thanks @rshingleton and @noxxi! I've merged this one at the command line.

2024-03-11 00:53 UTC, closed without merging